/*
 * AI Summarization API Route
 * Generates 3-sentence summaries using OpenAI or Groq APIs
 */

import { NextResponse } from 'next/server'

/**
 * @typedef {Object} SummarizeRequest
 * @property {string} text
 * @property {string} apiKey
 * @property {'openai'|'groq'|'anthropic'} provider
 */

/**
 * @typedef {Object} SummarizeResponse
 * @property {string} summary
 * @property {string} provider
 * @property {string} timestamp
 */

// LLM API configurations
const LLM_CONFIGS = {
  openai: {
    endpoint: 'https://api.openai.com/v1/chat/completions',
    model: 'gpt-3.5-turbo',
    maxTokens: 150
  },
  groq: {
    endpoint: 'https://api.groq.com/openai/v1/chat/completions',
    model: 'mixtral-8x7b-32768',
    maxTokens: 150
  },
  anthropic: {
    endpoint: 'https://api.anthropic.com/v1/messages',
    model: 'claude-3-haiku-20240307',
    maxTokens: 150
  }
}

/**
 * POST /api/summarize
 * Generates AI-powered summaries of repository content
 * @param {Request} request - The incoming request
 * @returns {Promise<Response>} JSON response with summary
 */
export async function POST(request) {
  try {
    // Parse and validate request body
    /** @type {SummarizeRequest} */
    const body = await request.json()
    
    if (!body.text || !body.apiKey || !body.provider) {
      return NextResponse.json(
        { error: 'Missing required fields: text, apiKey, and provider are required' },
        { status: 400 }
      )
    }

    if (!['openai', 'groq', 'anthropic'].includes(body.provider)) {
      return NextResponse.json(
        { error: 'Invalid provider. Must be "openai", "groq", or "anthropic"' },
        { status: 400 }
      )
    }

    // Get configuration for the selected provider
    const config = LLM_CONFIGS[body.provider]
    
    // Prepare the prompt for summarization
    const systemPrompt = `You are a technical summarizer. Summarize the given GitHub repository information in exactly 3 sentences. Focus on:
1. What the repository does (main purpose/functionality)
2. Key features or technologies used
3. Target use case or audience

Keep it concise, technical, and informative.`

    const userPrompt = `Please summarize this GitHub repository:\n\n${body.text}`

    // Prepare the API request payload based on provider
    let payload, headers
    
    if (body.provider === 'anthropic') {
      // Anthropic uses a different API format
      payload = {
        model: config.model,
        max_tokens: config.maxTokens,
        messages: [
          { 
            role: 'user', 
            content: `${systemPrompt}\n\n${userPrompt}` 
          }
        ]
      }
      
      headers = {
        'Content-Type': 'application/json',
        'x-api-key': body.apiKey,
        'anthropic-version': '2023-06-01'
      }
    } else {
      // OpenAI and Groq use the same format
      payload = {
        model: config.model,
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        max_tokens: config.maxTokens,
        temperature: 0.3,
        top_p: 1,
        frequency_penalty: 0,
        presence_penalty: 0
      }
      
      headers = {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${body.apiKey}`,
        ...(body.provider === 'groq' && {
          'User-Agent': 'AI-News-Aggregator/1.0'
        })
      }
    }

    console.log(`Making ${body.provider} API request for summarization`)

    // Make request to the LLM API
    const response = await fetch(config.endpoint, {
      method: 'POST',
      headers,
      body: JSON.stringify(payload)
    })

    if (!response.ok) {
      const errorText = await response.text()
      console.error(`${body.provider} API error:`, response.status, errorText)
      
      // Handle specific error cases
      if (response.status === 401) {
        return NextResponse.json(
          { error: 'Invalid API key. Please check your credentials.' },
          { status: 401 }
        )
      }
      
      if (response.status === 429) {
        return NextResponse.json(
          { error: 'Rate limit exceeded. Please try again later.' },
          { status: 429 }
        )
      }
      
      return NextResponse.json(
        { error: `${body.provider} API error: ${response.status}` },
        { status: 500 }
      )
    }

    const data = await response.json()
    
    // Extract the summary from the response based on provider
    let summary
    if (body.provider === 'anthropic') {
      summary = data.content?.[0]?.text?.trim()
    } else {
      summary = data.choices?.[0]?.message?.content?.trim()
    }
    
    if (!summary) {
      throw new Error('No summary generated by the AI model')
    }

    // Validate that we got approximately 3 sentences
    const sentenceCount = summary.split(/[.!?]+/).filter(s => s.trim().length > 0).length
    
    if (sentenceCount < 2) {
      console.warn(`Summary only contains ${sentenceCount} sentences, expected 3`)
    }

    console.log(`Successfully generated summary using ${body.provider}`)

    // Return the summary
    /** @type {SummarizeResponse} */
    const result = {
      summary,
      provider: body.provider,
      timestamp: new Date().toISOString()
    }

    return NextResponse.json(result)

  } catch (error) {
    console.error('Error in summarize API:', error)
    
    return NextResponse.json(
      { 
        error: error instanceof Error ? error.message : 'Failed to generate summary',
        provider: 'unknown',
        timestamp: new Date().toISOString()
      },
      { status: 500 }
    )
  }
}

/**
 * GET /api/summarize
 * Returns API information and supported providers
 * @returns {Promise<Response>} JSON response with API info
 */
export async function GET() {
  return NextResponse.json({
    message: 'AI Summarization API',
    supported_providers: ['openai', 'groq', 'anthropic'],
    method: 'POST',
    required_fields: ['text', 'apiKey', 'provider'],
    description: 'Generates 3-sentence summaries of repository content using AI'
  })
}